# Generated by Django 4.1.5 on 2023-02-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_recipe_ingredient_remove_recipe_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='location',
        ),
        migrations.AddField(
            model_name='staff',
            name='location',
            field=models.ManyToManyField(to='inventory.location'),
        ),
    ]
