# Generated by Django 4.1.5 on 2023-02-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_staff_location_staff_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
