# Generated by Django 4.1.5 on 2023-02-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('mililiter', 'Mililiter'), ('centiliter', 'Centiliter'), ('deciliter', 'Deciliter'), ('liter', 'Liter')], max_length=16),
        ),
    ]
