# Generated by Django 4.1.5 on 2023-02-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_ingredient_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifier',
            name='option',
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('modifier_option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.modifier')),
            ],
            options={
                'db_table': 'inventory_modifier_option',
            },
        ),
    ]
