# Generated by Django 4.1.5 on 2023-02-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_location_address_alter_modifier_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientStock',
            fields=[
                ('ingredient_stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('units_available', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
            ],
            options={
                'db_table': 'inventory_ingredient_stock',
                'unique_together': {('ingredient', 'location')},
            },
        ),
    ]
