# Generated by Django 4.1.5 on 2023-02-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_ingredientstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientstock',
            name='units_available',
            field=models.FloatField(default=0.0),
        ),
    ]
