# Generated by Django 4.1.5 on 2023-02-17 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_modifieroption_ingredient_alter_ingredient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAudit',
            fields=[
                ('stock_audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('delivery', 'Delivery'), ('sale', 'Sale'), ('waste', 'Waste')], editable=False, max_length=16)),
                ('units_change', models.FloatField(editable=False)),
                ('cost', models.FloatField(editable=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='inventory.ingredient')),
                ('location', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='inventory.location')),
                ('staff', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='inventory.staff')),
            ],
            options={
                'db_table': 'inventory_stock_audit',
            },
        ),
        migrations.CreateModel(
            name='SalesAudit',
            fields=[
                ('sales_audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_amount', models.FloatField(editable=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('location', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='inventory.location')),
                ('menu', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='inventory.menu')),
                ('staff', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='inventory.staff')),
            ],
            options={
                'db_table': 'inventory_sale_audit',
            },
        ),
    ]
