# Generated by Django 4.1.5 on 2023-02-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stockaudit_salesaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesaudit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockaudit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
